version: '3.7'

services:
    exabgpapi:
        build: ./exabgp
        ports:
            - '179:179'
        volumes:
            - './exabgp/exabgp.conf:/etc/exabgp/exabgp.conf'
        container_name: exabgpapi
        restart: always
        depends_on:
            - bgplsapi
            - bgplsapi-worker

    bgplsapi:
        build: ./bgpls-api
        ports:
            - '5000:5000'
        container_name: 'bgpls-api'
        restart: always
        env_file:
            - ./bgpls-api/env/app
        depends_on:
            - rabbitmq

    bgplsapi-worker:
        build: 
            context: ./bgpls-api
            dockerfile: Dockerfile-worker
        container_name: 'bgpls-api-worker'
        restart: always
        env_file:
            - ./bgpls-api/env/app
            - ./bgpls-api/env/mongodb
        depends_on:
            - rabbitmq

    mongodb:
        image: 'mongo'
        container_name: 'mongodb'
        restart: always
        env_file:
            - ./bgpls-api/env/mongodb
        volumes:
            - ./mongo-data:/data/db:z

    rabbitmq:
        image: rabbitmq:3.8.16-management
        container_name: rabbitmq
        volumes:
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/log/:/var/log/rabbitmq/
            - ./rabbitmq/etc/:/etc/rabbitmq/
        environment:
            RABBITMQ_DEFAULT_USER: "bgpls"
            RABBITMQ_DEFAULT_PASS: "4D6JD6LwwH9!Y-ot" 
        ports:
            - 5672:5672
            - 15672:15672

volumes:
    exabgpapi:
        driver: local
    bgplsapi:
        driver: local
