version: '3.7'

services:
    exabgpapi:
        build: ./exabgp
        ports:
            - '179:179'
        volumes:
            - './exabgp/exabgp.conf:/etc/exabgp/exabgp.conf'
        container_name: exabgpapi
        restart: always

    bgplsapi:
        build: ./bgpls-api
        ports:
            - '5000:5000'
        container_name: 'bgpls-api'
        restart: always
        env_file:
            - ./bgpls-api/env/app

    bgplsapi-worker:
        build: 
            context: ./bgpls-api
            dockerfile: Dockerfile-worker
        container_name: 'bgpls-api-worker'
        restart: always
        env_file:
            - ./bgpls-api/env/app
            - ./bgpls-api/env/mongodb

    mongodb:
        image: 'mongo'
        container_name: 'mongodb'
        restart: always
        env_file:
            - ./bgpls-api/env/mongodb
        volumes:
            - ./mongo-data:/data/db:z

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        volumes:
            - ./rabbitmq/etc/:/etc/rabbitmq/:z
            - ./rabbitmq/data/:/var/lib/rabbitmq/:z
            - ./rabbitmq/logs/:/var/log/rabbitmq/:z
        env_file:
            - ./rabbitmq/.env
        ports:
            - 5672:5672
            - 15672:15672

volumes:
    exabgpapi:
        driver: local
    bgplsapi:
        driver: local
