FROM python:3.8-slim

RUN apt-get update \
    && pip3 install --upgrade pip

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app
RUN pip3 install -r requirements.txt
COPY . /app

ENTRYPOINT [ "python3" ]
CMD [ "bgpls_rabbitmq_worker.py" ]
